// ACTION TYPES
const FETCH_ALL_CAMPUSES = "FETCH_ALL_CAMPUSES";
const FETCH_CAMPUS = "FETCH_CAMPUS";
const ADD_CAMPUS = "ADD_CAMPUS";
const DELETE_CAMPUS = "DELETE_CAMPUS";

export default
{
    FETCH_ALL_CAMPUSES,
    FETCH_CAMPUS,
    ADD_CAMPUS,
    DELETE_CAMPUS,
}