// ACTION TYPES
const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
const FETCH_STUDENT = "FETCH_STUDENT";
const ADD_STUDENT = "ADD_STUDENT";
const DELETE_STUDENT = "DELETE_STUDENT";

export default
{
    FETCH_ALL_STUDENTS,
    FETCH_STUDENT,
    ADD_STUDENT,
    DELETE_STUDENT,
}